language: python
python:
  - "2.7"
install:
  - pip install -e . --use-mirrors
  - pip install django-jinja --upgrade --use-mirrors
  - pip install jinja2 --upgrade --use-mirrors
  - pip install coveralls --upgrade --use-mirrors
script:
  - coverage run --source=sr setup.py test
notifications:
  email:
    recipients:
      - jespinog@gmail.com
    on_success: change
    on_failure: change
after_success:
  - coveralls
